### ISSUE TITLE
Why not use a TX capable SDR for UAT signal generation?

### ISSUE THREAD

**Issue by saedelman** [lyusupov/UAT-test-signal#1]
I'm curious, why use a discrete transceiver chip (CC1310) for this instead of a TX capable SDR, like you have used for your 1090ES ADSB-out project? Would it not be much simpler to use a TX capable SDR (such as the LimeSDR mini) to generate UAT 978 signals?

**Comment by lyusupov** [comment]
This GitHub repo is a subsidiary of a larger [SoftRF project](https://github.com/lyusupov/SoftRF).
I've made this generator with the same hardware that I use for my UAT receiver.

Some sort of SDR UAT test signals were already generated by Chris Young for his Stratux project:
https://github.com/cyoung/adsbtest/blob/master/uat.go
I am not sure if that Go code is fully operational. Ask him.
