### ISSUE TITLE
Could this be done with a 915mhz LoRa Radio

### ISSUE THREAD

**Issue by JohnDoeKyrgyz** [lyusupov/UAT-test-signal#4]
Admittedly this is not really an issue but more of a question. Do you know whether or not it would be possible to implement this technique using a LoRa radio?

Your SoftRF project and GxAirCom use the LoRa radio to implement FLARM and FANET. Being able to transmit ADS-B on these devices to make free flight aircraft visible would be very useful.

**Comment by lyusupov** [comment]
Read tech specs of your LioRa radio, such as:
- max..data rate
- -max. frequency range
then compare them with the ADS-B ones.
